route:
  group_wait: 1s
  group_interval: 1s
  repeat_interval: 1m
  # If an alert isn't caught by a route, send it slack.
  receiver: slack_general
  routes:
  # Send severity=slack alerts to slack.
  - match:
      severity: slack
    receiver: slack_general

receivers:
- name: slack_general
  slack_configs:
  - api_url: https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK_URL
    icon_url: https://avatars3.githubusercontent.com/u/3380462
    send_resolved: true
    channel: '#alerts'
    title: '{{ template "custom_title" . }}'
    text: '{{ template "custom_slack_message" . }}'

templates:
- /home/ubuntu/alertmanager-0.14.0.linux-amd64/notifications.tmpl
